version: '3'
services:
  analytics-api:
    build: .
    command: "yarn start:dev"
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    environment:
      - PORT=3000
      - API_BASE_URL=https://jsonplaceholder.typicode.com